IPv4dev=eth0
IPv4addr=192.168.115.0/24
IPv4gw=192.168.115.7
dhcpReserv=0
pivpnenableipv6=0
install_user=pi
VPN=openvpn
pivpnNET=10.8.0.0
subnetClass=24
pivpnPROTO=udp
pivpnPORT=1194
pivpnDNS1=192.168.115.254
pivpnDNS2=0.0.0.0
pivpnHOST=pivpn.example.com
pivpnENCRYPT=256
pivpnSEARCHDOMAIN=searchdomain.example.com
TWO_POINT_FOUR=1
USE_PREDEFINED_DH_PARAM=1
UNATTUPG=1
